/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.teamX.server;

import edu.duke.ece651.teamX.shared.*;
import java.net.ServerSocket;
import java.net.Socket;
import java.io.IOException;
import java.util.Scanner;
import java.util.HashMap;
import java.util.ArrayList;
import java.util.concurrent.locks.*;

public class App {

  private HashMap<String, String> namePasswordDic;
  private ArrayList<Game> GameList;
  private ReadWriteLock gameLock;
  private ReadWriteLock nameLock;

  public App() {
    namePasswordDic = new HashMap<String, String>();
    GameList = new ArrayList<Game>();
    gameLock = new ReentrantReadWriteLock();
    nameLock = new ReentrantReadWriteLock();
  }

  // private int getPlayerNum(Scanner input) {
  //   int playerNum;
  //   // Prompt for first integer input for player number
  //   System.out.print("Enter the player number(between 2 and 4): ");
  //   while (!input.hasNextInt() || (playerNum = input.nextInt()) < 2 || playerNum > 4) {
  //     input.nextLine(); // clear input buffer
  //     System.out.print("Invalid input. Please enter a positive integer between 2 and 4: ");
  //   }
  //   return playerNum;
  // }

  private int getPort(Scanner input) {
    int port;
    // Prompt for second integer input for port number
    System.out.print("Enter the port number(between 1 and 65535): ");
    while (!input.hasNextInt() || (port = input.nextInt()) < 1 || port > 65535) {
      input.nextLine(); // clear input buffer
      System.out.print("Invalid input. Please enter a positive integer between 1 and 65535: ");
    }
    return port;
  }

  public static void main(String[] args) throws IOException, ClassNotFoundException {
    App app = new App();
    Scanner input = new Scanner(System.in);
    int port = app.getPort(input);
    input.close();
    ServerSocket ss = new ServerSocket(port);
    while (true) {
      try {
        Socket pSocket = ss.accept();
        Thread adminT = new Thread(
            new Admin(app.namePasswordDic, app.GameList, pSocket, app.gameLock, app.nameLock));
        adminT.start();
      } catch (Exception e) {
        System.out.println(e.getMessage());
      }
    }
  }

}
