before_script:
  - hostname
  - whoami
  - pwd
  - ls -la
#  - docker --version

stages:
  - build
  - test
  - qodana
  - code_quality
  - page


build:
  tags:
    - ece651
  stage: build
  script: docker build --build-arg LOCAL_USER_ID=`id -u`  --tag citest .

test:
  tags:
    - ece651
  stage: test
  script: scripts/run-tests-in-docker.sh
  artifacts:
    paths:
      - coverage

qodana:
  stage:
    qodana
  image:
    name: jetbrains/qodana-jvm:2022.3-eap
    entrypoint: [ "" ]
  script:
    - qodana --save-report --results-dir=$CI_PROJECT_DIR/qodana
      --report-dir=$CI_PROJECT_DIR/qodana/report
  artifacts:
    paths:
      - qodana/report/
    expose_as: 'Qodana report'

include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  stage:
    code_quality
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [ gl-code-quality-report.html ]

pages:
  stage: page
  tags:
    - ece651
  dependencies:
    - qodana
    - code_quality
  script:
    - cp -r qodana/report/ public/
    - cp gl-code-quality-report.html public/
  artifacts:
    paths:
      - public
