/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.teamX.client;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.net.Socket;
import java.util.Scanner;
public class App {

  public static void main(String[] args) throws IOException, ClassNotFoundException {
    int port;
    if (args.length != 1) {
      System.out.println("Please provide port(integer) as a command-line argument.");
      return;
    } else {
      try {
        port = Integer.parseInt(args[0]);
      } catch (NumberFormatException e) {
        System.out.println("Invalid integer provided. Please provide a valid integer.");
        return;
      }
    }
    Socket clientSocket = new Socket("localhost", port);
    BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
    PrintStream out = System.out;
    UserInReader uir = new UserInReader(input, out);
    Client client = new Client(clientSocket, input, out);
    client.init();

    client.playTurns();
  }
}
