/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.teamX.client;

import edu.duke.ece651.teamX.shared.Communicate;
import edu.duke.ece651.teamX.shared.MyName;
import java.io.IOException;
import java.net.Socket;
import org.checkerframework.checker.units.qual.C;


public class App {

  public static void main(String[] args) throws IOException {
    Socket socket = new Socket("localhost", 4444);
    Communicate communicate = new Communicate();
    String send_str = "hello world\n";
    communicate.sendObject(socket, send_str);

  }
}
